version: '3.7'
services:
  
  benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
  
  postgres:
    image: postgres:14
    container_name: benchmark-postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"