version: '3.7'
services:

  benchmark:
    container_name: benchmarks
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"